### ISSUE TITLE
fftBuffer.subdata is not a function

### ISSUE THREAD

**Issue by devdevnullnull** [substack/regl-component#2]
Declaring a regl buffer using ` rc.regl.buffer({})`, where rc is the return value of `reglComponent.create()` produces this error when trying to run the subdata method. 

If I log that buffer it outputs `function dfn/</<()` (appearing as a function), but logging the execution of the buffer/function returns `undefined`

Calling other types of regl commands (like rc.regl.clear or rc.regl.frame) works

**Comment by substack** [comment]
Thanks for logging this issue, I think there are some remaining pieces (like textures) that can get mixed up if they're created before the context is initialized.

**Comment by substack** [comment]
This shouldn't be a problem now in v3 since there are no longer deferred regl instances and less wrapping. The API update is that now you've got to listen to a `'regl'` event on the `rc` instance instead of using a deferred `rc.regl` instance.
